name: google_places_autocomplete_text_field
description: A fully customizable Google Places autocomplete TextFormField for Flutter iOS, Android and Web.
version: 0.1.2
homepage: https://github.com/julienandco/google_places_autocomplete_text_field

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
