name: google_places_autocomplete_text_field
description: A fully customizable Google Places autocomplete TextFormField for Flutter iOS, Android and Web.
version: 2.0.3
homepage: https://github.com/julienandco/google_places_autocomplete_text_field

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  rxdart: ^0.28.0
  async: ^2.13.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
